import localFont from "next/font/local";
import LoadingPage from "./components/LoadingPage";
import "./globals.css";
import { Suspense } from "react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Suspense fallback={<LoadingPage/>}><div>{children}</div></Suspense>
      </body>
    </html>
  )
}
